### ISSUE TITLE
SY-UI-002 Font and Photo layout

### ISSUE THREAD

**Issue by mag9073** [mag9073/COMP72070_Sec3_Group9_Winter_2024#14]
Noted font and photo overlap issue, word "Park" is cut off to "Pa."
Will investigate and improve to resolve issue.
<img width="1280" alt="Screenshot 2024-03-05 125710" src="https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/146022076/c3081814-1446-447c-8265-cb5264e729d0">

**Comment by hsihak** [comment]
I will reopen the issue to add proof of the fix.

**Comment by hsihak** [comment]
**Purpose:** 
 We have successfully resolved the issue by introducing grid to the layout and made it responsive to various text length. Please refer to the screenshot below :) 
 
 **Screenshot of the After:**

![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/be47db17-21b9-4152-a2ee-a0747c5fa7a5)
