### ISSUE TITLE
SY-UI-005 issue with park review being cut off

### ISSUE THREAD

**Issue by mag9073** [mag9073/COMP72070_Sec3_Group9_Winter_2024#25]
park reviews are being cut off to only 2 lines visible. more review wording is hidden. same for all parks, 2 given as example here. 

<img width="1280" alt="Screenshot 2024-03-07 185225" src="https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/146022076/25e933a9-bd2b-4ede-9c05-c22f81d3bd1f">
<img width="1280" alt="Screenshot 2024-03-07 185254" src="https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/146022076/e77d06ff-e43d-4936-8ab7-7e2424fb70b6">

**Comment by hsihak** [comment]
Hello Michelle, 

The issue has been resolved now. We solved it by introducing grid and set overflow to auto. Even though you cannot see but if there are more than 3 reviews then there will be hidden overflow scrollbar.  Please refer to the screenshot of the After that can be found below or the Test Log Screenshots word document.  I will close the issue now!!!! :) 

![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/7730beaf-261d-4f46-b7df-238ce414cbe7)
